openapi: 3.0.0
info:
  title: Social App
  description: Our first Social App at here - Aayush
  version: 1.0.1

servers:
  - url: http://localhost:4000/api/v1
    description: localhost version of my app
  - url: https://socialapp-ayush.herokuapp.com/api/v1
    description: Heroku app version of the social app
  
components:
  securitySchemes:

    BasicAuth:
      type: http
      scheme: basic

    BearerAuth:
      type: http
      scheme: bearer

paths:
  /instagram:
    get:
      summary: returns username, followers and follows for instagram
      responses:
        '200': #status code
          description: return an object
          content:
            application/json:
              schema:
                type: object
                properties:
                  username:
                    type: string
                  followers:
                    type: string
                  follows:
                    type: string
  /linkedin:
    get:
      summary: returns username, followers and follows for linkedin
      responses:
        '200': #status code
          description: return an object
          content:
            application/json:
              schema:
                type: object
                properties:
                  username:
                    type: string
                  followers:
                    type: string
                  follows:
                    type: string
  /twitter:
    get:
      summary: returns username, followers and follows for twitter
      responses:
        '200': #status code
          description: return an object
          content:
            application/json:
              schema:
                type: object
                properties:
                  username:
                    type: string
                  followers:
                    type: string
                  follows:
                    type: string
  /{token}:
    get:
      summary: returns whatever there is in parameter
      parameters:
        - name: token
          default: aayush
          in: path
      responses:
        '200': #status code
          description: return an object
          content:
            application/json:
              schema:
                type: object
                properties:
                  params:
                    type: string